/**
  *****************************************************************************
  * @title   dht11.c
  * @author  muhittin_kaplan
  * @date    13 May 2014
  * @brief   DHT11 with stm32f4
  *******************************************************************************
  */
////// The above comment is automatically generated by CoIDE ///////////////////

#include "dh11_driver.h"
#include "math.h"

#define GPIO_PORT	GPIOA
#define GPIO_PIN	GPIO_Pin_5
#define GPIO_RCC	RCC_APB2Periph_GPIOA

GPIO_InitTypeDef  GPIO_InitStructure;
TIM_TimeBaseInitTypeDef TIM_TimeBaseStructure = { 0 };

void DHT11initTIM2(void)
{
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);
	TIM_TimeBaseStructure.TIM_Period = 65535;//1us
	TIM_TimeBaseStructure.TIM_Prescaler = 71;		//1us counter
	TIM_TimeBaseStructure.TIM_ClockDivision = 0;
	TIM_TimeBaseStructure.TIM_CounterMode = TIM_CounterMode_Up;
	TIM_TimeBaseInit(TIM2, &TIM_TimeBaseStructure);
	TIM_Cmd(TIM2, ENABLE);
}

void DHT11initGPIOasOutput(void){

	 /* GPIOD Periph clock enable */
	RCC_APB1PeriphClockCmd(GPIO_RCC, ENABLE);

	/* Configure PD12, PD13, PD14 and PD15 in output pushpull mode */
	GPIO_InitStructure.GPIO_Pin = GPIO_PIN;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init(GPIO_PORT, &GPIO_InitStructure);

}


void DHT11initGPIOasInput(void){

	 /* GPIOD Periph clock enable */
	RCC_APB1PeriphClockCmd(GPIO_RCC, ENABLE);
	GPIO_InitStructure.GPIO_Pin = GPIO_PIN;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IPD;
	GPIO_Init(GPIO_PORT, &GPIO_InitStructure);
}


void DHT11_delay_us(int us){

	TIM2->CNT = 0;
	while((TIM2->CNT) <= us);
}

float Fahrenheit(u8 celsius)
{
        return 1.8 * celsius + 32;
}

u32 get_timer_cnt()
{
	return TIM2->CNT;
}

float Kelvin(u8 celsius)
{
        return celsius + 273.15;
}

double dewPointFast(double celsius, double humidity)
{
      double a = 17.271,
             b = 237.7,
             temp ;

      temp = (a * celsius) / (b + celsius) + log(humidity/100);

      return  (b * temp) / (a - temp);;
}




void DHT11Read(u8 *Rh,u8 *RhDec,u8 *Temp,u8 *TempDec, u8 *ChkSum)
{
	DHT11_delay_us(5000000);
	u8 temp;
	u8 j;
	u8 i;
	u8 Value[5]={0x00,0x00,0x00,0x00,0x00};

	DHT11initGPIOasOutput();
	GPIO_ResetBits(GPIO_PORT,GPIO_PIN);
	DHT11_delay_us(18000);
	GPIO_SetBits(GPIO_PORT,GPIO_PIN);
	DHT11_delay_us(40);
	DHT11initGPIOasInput();

	//80us lik presence										//
	while(!GPIO_ReadInputDataBit(GPIO_PORT,GPIO_PIN)){}		//52us 0 level
															//dht11 response and start to send signal 0-1
	while(GPIO_ReadInputDataBit(GPIO_PORT,GPIO_PIN)){}			//80us 1 level
															//


	for (j = 0; j < 5; ++j) {//5*8 toplam 40 bit Rh,rhdec,temp,tempdec,chksum
		for (i = 0; i < 8; ++i) {

			while(!GPIO_ReadInputDataBit(GPIO_PORT,GPIO_PIN)){} //0 olan boþ geçiliyor

			TIM_SetCounter(TIM2,0);//Sayýcýyý Sýfýrla
			while(GPIO_ReadInputDataBit(GPIO_PORT,GPIO_PIN)){}

				temp=TIM_GetCounter(TIM2);//sayýcý deðerini al (böylelikle zaman hesaplanýyor)

			if (temp<30) {
				Value[j]=Value[j]<<1;
				}
			else {
				Value[j]=Value[j]<<1;
				Value[j] =Value[j]+1;
				}
		}
	}
	*Rh=Value[0];
	*RhDec=Value[1];
	*Temp=Value[2];
	*TempDec=Value[3];
	*ChkSum=Value[4];
}
