/**
  *****************************************************************************
  * @title   dht11.h
  * @author  muhittin_kaplan
  * @date    13 May 2014
  * @brief   DHT11 with stm32f4
  *******************************************************************************
  */
////// The above comment is automatically generated by CoIDE ///////////////////

#include "stm32f10x.h"
#include "stm32f10x_gpio.h"
#include "stm32f10x_rcc.h"
#include "stm32f10x_tim.h"
#include "stm32f10x_usart.h"
#include "misc.h"
#include "stdio.h"
#include "math.h"

void DHT11Read(u8 *Rh,u8 *RhDec,u8 *Temp,u8 *TempDec, u8 *ChkSum);
float Fahrenheit(u8 celsius);
float Kelvin(u8 celsius);
double dewPointFast(double celsius, double humidity);
void DHT11_delay_us(int us);
void DHT11initGPIOasInput(void);
void DHT11initGPIOasOutput(void);
void DHT11initTIM2(void);

uint8_t DHT22_Check_Response (void);
uint8_t DHT22_Read (void);
void DHT22_Start (void);


u32 get_timer_cnt();
